### ISSUE TITLE
Référence à un article de la Loi Lemaire à revoir dans le guide sur l'ouverture du code

### ISSUE THREAD

**Issue by fBedecarrats** [etalab/guides.etalab.gouv.fr#106]
Bonjour,
La section [cadre juridique du guide sur l'ouverture des codes sources](https://guides.etalab.gouv.fr/logiciels/cadre-juridique/) fait référence à un l'article 46, II, 4 de la loi pour une République numérique.
Le [texte de loi auquel on fait référence](https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000033202746?r=FQQfW4ALju) contient un article 46 qui ne semble pas avoir de lien direct avec le sujet évoqué. Par ailleurs c'est article ne contient pas d'alinéas II, 4.
Est-ce qu'il n'y a pas une erreur ?
Bien cordialement
FB

**Comment by bzg** [comment]
Bonjour, merci d'avoir signalé ce problème.  J'ai corrigé en retirant la référence, qui effectivement semble hors sujet.
