### ISSUE TITLE
API Geo - doc adresse

### ISSUE THREAD

**Issue by ThomasG77** [etalab/guides.etalab.gouv.fr#151]
Related to #148

**Comment by agarrone** [comment]
- [ ] Relecture par @agarrone

**Comment by agarrone** [comment]
I've proposed changes here : https://github.com/webgeodatavore/guides.etalab.gouv.fr/pull/4
@abulte your insight (especially on the second part on the tools we advocates) is more than welcome 🙂  
Notes can be found here (if it's more easy to comment) : https://www.notion.so/apigouv/Guide-adresse-f9b2e7c903d3479294aaa31e78fb261f#dd53710448884cd08dd49990f387e33a
