### ISSUE TITLE
Deux liens pas bons / cassés dans le guide des algorithmes publics

### ISSUE THREAD

**Issue by everdha** [etalab/guides.etalab.gouv.fr#172]
1. Dans section "les algos publics" https://guides.etalab.gouv.fr/algorithmes/guide/#les-algorithmes-publics-enjeux-et-obligations le lien vers le guide sur l'ouverture des codes sources renvoie vers sa version sur github, ce qui peut être perturbant pour un non informaticien, j'imagine que l'idée  est de renvoyer vers le guide sur le site etalab : https://guides.etalab.gouv.fr/logiciels/
2. Dans section "comment contribuer" https://guides.etalab.gouv.fr/algorithmes/guide/#comment-contribuer le lien "version éditable" vers le guide sur github n'est pas bon.

**Comment by bzg** [comment]
Merci d'avoir remonté ces deux soucis !  Ils sont corrigés dans le dépôt, mais pas encore publié: il y a un truc qui coince dans les GitHub actions à la publication, je vais ouvrir une issue distincte pour ça.
