### ISSUE TITLE
CI cassée au niveau de la génération des PDF: les mises à jour ne sont plus déployées

### ISSUE THREAD

**Issue by bzg** [etalab/guides.etalab.gouv.fr#173]
Hello!  En poussant quelques commits ce matin, la CI ne publie plus.

Voir https://github.com/etalab/guides.etalab.gouv.fr/runs/6744125724?check_suite_focus=true

Quelqu'un a une idée de ce qui peut coincer?

**Comment by abulte** [comment]
Fixed by #169 

NB: creating PRs for changes is better

**Comment by bzg** [comment]
Thanks for fixing this!

> NB: creating PRs for changes is better

OK, I've created https://github.com/etalab/guides.etalab.gouv.fr/issues/175
so that we can explain the process.
