### ISSUE TITLE
Mise en cohérence du guide "qualite / 3-documenter-les-donnees" et du guide "producteurs-schemas"

### ISSUE THREAD

**Issue by loco-philippe** [etalab/guides.etalab.gouv.fr#204]
Dans la construction d'un jeu de données, le guide "qualite / 3-documenter-les-donnees" fait référence à une étape de "description du modèle de données" préalable  à celle de documentation d'un schéma de données (mais ne fait pas le lien explicitement avec le guide "producteurs-schemas").

Réciproquement, le guide "producteurs-schemas" ne fait pas référence à l'étape préalable de construction du modèle de données précisée dans le guide "qualite / 3-documenter-les-donnees". 

Mon avis :

- l'étape modèle de données me parait fondamentale car c'est à cette étape que l'on formalise les dépendances qui existent entre données (la notion de modèle de données est générale et ne se limite pas une approche multi-fichiers). C'est aussi un bon outil pour échanger et se comprendre. Les dépendances identifiées dans le modèle de données peuvent ensuite être formalisées dans le schéma de données et vérifiées dans la phase de production des données (cf [proposition de méthodologie](https://nbviewer.org/github/loco-philippe/Environmental-Sensing/blob/main/property_relationship/FR_methodology.ipynb).
- Les deux guides se recouvrent en partie, mais sans maintenir la cohérence entre les deux, ce qui brouille le message. 
- Plusieurs solutions sont possibles :
       -  fusionner les deux (ce qui revient à intégrer le guide "producteurs-schemas" dans le guide "qualite / 3-documenter-les-donnees" 
       - maintenir deux guides mais séparer les concepts : Ne garder dans le premier que la démarche, le processus et la méthodologie générale (en réintégrant notamment le phasage décrit dans le guide "producteurs-schemas") et dans le second que ce qui est spécifique de l'outil "schéma" (principe, mise en œuvre, gestion/suivi). Cette approche permettrait également d'ajouter au fur et à mesure des évolutions des outils, par exemple un outil "modèle de données", un outil "métadonnées", un outil "score qualité", un outil "représentation multi-fichiers"...

**Comment by Pierlou** [comment]
Bonjour Philippe, merci pour ce retour. Nous avons modifié les guides récemment en prenant en compte vos retours de la dernière fois. Une attention particulière a été portée à la distinction des termes "modèle" et "schéma". Ces modifications répondent-elles tout ou partie aux considérations ci-dessus ?

**Comment by loco-philippe** [comment]
Merci Pierlou pour cette prise en compte plus rapide que la demande !!!

Oui, ça répond en grande partie. Il restait quelques modifications que je me suis proposé d'apporter au travers de PR#205.
-> à discuter si besoin

Bonne journée
