### ISSUE TITLE
Retours utilisateurs

### ISSUE THREAD

**Issue by mathildehg** [etalab/guides.etalab.gouv.fr#41]
Hello, 
Afin de récolter le plus de retours possibles sur le guide, serait-il possible de proposer un form ou un module de commentaire pour les lecteurs ? 
La solution de github fonctionne bien, mais elle reste une grosse barrière à l'entrée. Surtout si on garde en tête que les lecteurs des guides pourront être des agents administratifs qui n'ont pas forcément de compétences techniques ou de connaissance de github. 

Dites-moi ce que vous en pensez !

**Comment by abulte** [comment]
Mettre une adresse email ?

**Comment by mathildehg** [comment]
J'aimais bien l'idée que les commentaires soient visibles de tous, mais à minima cela peut être une solution : quelle adresse ?

**Comment by abulte** [comment]
On peut utiliser ouverture@data.gouv.fr ou créer guides@etalab.gouv.fr. En tout cas il faudra répondre 🙃.

Autre solution possible : envoyer vers le forum Etalab.

**Comment by mathildehg** [comment]
ouverture@data.gouv.fr ne me semble pas très satisfaisant puisque cela crée de la confusion. Après cela signifie créer un nouvel alias... Ca me convient d'en être responsable et de rediriger les demandes aux respos guides associés (open data, open source, open algo).

**Comment by AntoineAugusti** [comment]
Actuellement on a un lien [vers le formulaire de contact d'Etalab](https://www.etalab.gouv.fr/contact) qui se trouve dans la barre de navigation en haut à droite.

Est-ce suffisant ?

**Comment by abulte** [comment]
C'est pas franchement un problème de créer un nouvel alias. Creusons quand même la piste du forum, ça peut être vertueux /cc @bzg.

**Comment by mathildehg** [comment]
@AntoineAugusti tu suggères de proposer le même formulaire sur guide ou de passer par le blog Etalab ?

**Comment by AntoineAugusti** [comment]
Actuellement on un lien nommé "Contacter Etalab", qui renvoie vers le formulaire de contact.

Je me demande :
- si cette solution en tant que telle te convient
- si les catégories proposées là-bas sont suffisantes
- si tu souhaites la création d'un alias `guides` (mais faut y répondre)
- ou comme le suggère @abulte on propose de laisser un message sur le forum

**Comment by mathildehg** [comment]
Ah oui, je n'avais pas assez bien regardé ! La solution me convient si nous pouvons ajouter une catégorie dans "type de demande". Qu'en pensez-vous ? 

Le forum pourquoi pas, mais est-ce qu'il faut s'inscrire pour soumettre un commentaire ?

**Comment by AntoineAugusti** [comment]
> Ah oui, je n'avais pas assez bien regardé ! La solution me convient si nous pouvons ajouter une catégorie dans "type de demande". Qu'en pensez-vous ?

On peut ajouter une catégorie. Ça implique la création d'un nouvel alias. Et donc de répondre à cet alias.


> Le forum pourquoi pas, mais est-ce qu'il faut s'inscrire pour soumettre un commentaire ?

L'inscription est obligatoire pour démarrer un nouveau sujet ou répondre. Pas pour consulter.

**Comment by mathildehg** [comment]
Que préférez-vous ? 
J'ai une préférence pour la solution qui coute le moins au lecteur

**Comment by AntoineAugusti** [comment]
Le formulaire de contact est sûrement la solution qui coûte le moins aux lecteurs. Il faut se tenir à répondre et prendre en compte les remarques.

On perd la publicité des retours.

**Comment by AntoineAugusti** [comment]
@abulte, peux-tu créer un alias `guides@data.gouv.fr` et mettre @mathildehg et moi dedans (tu peux ajouter d'autres personnes bien sûr). Je n'ai pas accès à PFA.

Une fois ceci fait, je mettrai un item pour les guides sur le formulaire de contact https://www.etalab.gouv.fr/contact.

Selon le volume et la nature des messages reçus, on pourra envisager de mettre en place une autre solution

**Comment by abulte** [comment]
Done, mais avec `guides (arobas) etalab.gouv.fr`, ça me parait plus cohérent ?

**Comment by AntoineAugusti** [comment]
C'est très bien, merci👍 Je ne savais pas qu'on faisait des adresses en etalab.gouv.fr aussi.

**Comment by AntoineAugusti** [comment]
✅Liste testée
✅ Choix "Guides" ajouté sur [le formulaire de contact](https://www.etalab.gouv.fr/contact)

Je pense que l'on peut fermer cette issue @mathildehg et faire un point à l'usage ? Tu pourras inviter les gens à faire un retour sur la liste guides@etalab.gouv.fr

**Comment by mathildehg** [comment]
Merci à vous deux ! 
De mon coté, c'est bon pour cette issue :)
