### ISSUE TITLE
Rename to guides.etalab.gouv.fr

### ISSUE THREAD

**Issue by abulte** [etalab/guides.etalab.gouv.fr#43]
Cf https://github.com/etalab/code.etalab.gouv.fr/issues/78

**Comment by AntoineAugusti** [comment]
This is straightforward from the repo settings. Do we need to do something first to avoid breaking things?

**Comment by abulte** [comment]
I don't think we need to do anything special, just check the `now` integration afterwards. I just did not want to do it brutally in case someone objected.
