### ISSUE TITLE
Image non utilisée

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/guides.etalab.gouv.fr#48]
L'[image suivante](https://github.com/etalab/guides.etalab.gouv.fr/blob/master/juridique/images/cadre_juridique_od.jpg) est présente dans le guide juridique mais non utilisée.

Faut-il la mettre quelque part ? La supprimer ?

**Comment by mathildehg** [comment]
Nous pouvons la supprimer 
Merci pour ta vigilance !
