### ISSUE TITLE
Dire "Données" plutôt que "Jeux de données"

### ISSUE THREAD

**Issue by bzg** [etalab/guides.etalab.gouv.fr#73]
La page https://guides.etalab.gouv.fr/accueil.html donne accès à deux guides contenant "Jeux de données" dans leur titre.

- Quels jeux de données doivent être publiés en open data ?
- Comment publier des jeux de données sur data.gouv.fr ? 

Ces deux guides portent sur les données administratives en général et l'expression "jeux de données" désigne plutôt des données classiques, tabulaires.

Il est souvent difficile de faire comprendre que des "données textuelles" relèvent bien des données administratives à publier en open data.  Je suggère simplement de dire "données" à la place de "jeux de données".  Si c'est OK pour vous, je fais la PR.

**Comment by bzg** [comment]
Petit bump - @mathildehg dis-moi juste go-no-go et je fais la PR.  Bonne journée !

**Comment by mathildehg** [comment]
C'est bon de mon côté ! Désolée pour ce délai de réponse...
Merci @bzg

**Comment by bzg** [comment]
OK! Fait dans [cette PR](https://github.com/etalab/guides.etalab.gouv.fr/pull/84) que je me suis autorisé à merger.
