### ISSUE TITLE
Déplacer la "liste des algorithmes publiés" du guide des algorithmes publics vers celui des codes sources

### ISSUE THREAD

**Issue by schignard** [etalab/guides.etalab.gouv.fr#75]
Le guide des algorithmes publics contient une liste tenue à jour par @bzg sur les algorithmes publiés (CNAF, calculateur du code des impôts, etc.). 

Je crains que la localisation de cette page à cet endroit là (dans le guide des algorithmes) contribue à entretenir une certaine confusion dans l'esprit de nos publics qui ont déjà parfois tendance à mélanger les différentes obligations issues de la Loi pour une République numérique. 

Ce guide traite des obligations de transparence des algorithmes, qui est un principe distinct (et tout à fait complémentaire) de celui de publication des codes-sources. Dans un cas on doit fournir des informations aux personnes concernées (droit à l'explication du fonctionnement et des résultats d'un algorithme), dans l'autre on doit publier un code-source.
 
Je propose deux choses: 
- que l'on déplace cette liste dans le guide des codes-sources (ou à tout le moins qu'elle ne figure plus à l'endroit où elle est actuellement),
- qu'on rajoute clairement et explicitement dans le guide des algorithmes publics que d'autres ressources sont disponibles, dont le guide sur la publication des codes sources

**Comment by bzg** [comment]
Salut @schignard - oui, effectivement, la présentation de cette page n'est pas idéale.

Vu que la page s'intitule « Liste d'algorithmes publics », comment la remplir si on n'y fait plus apparaître les liens vers les codes sources des algorithmes publics aujourd'hui présentés ?

Autrement dit, est-ce qu'il y a des **exemples** permettant d'illustrer les obligations complémentaires que tu évoques (droit à l'explication du fonctionnement et des résultats d'un algorithme)? Le pdf d'explication de Parcoursup vient à l'esprit, et peut-être des supports du côté de La Bonne Boîte, mais y en a-t-il assez pour y consacrer une page ?

La solution idéale pour moi serait un tableau avec une liste d'algorithmes publics, une colonne « explication du fonctionnement et des résultats » puis une autre « code source » (remplie ou pas) - cela montrerait la complémentarité.

Je crois qu'il faut distinguer la publication d'un code source comme obligation relevant de l'open data et la publication d'un code source comme faisant partie des explications permettant d'être transparent sur le fonctionnement d'un algorithme.  Mais les dépôts présents sur cette page n'auraient pas vraiment leur place dans le guide de publication des codes sources : les codes sources de ces dépôts sont trop spécifiques, les README souvent mal écrits, etc.  Ce sont des codes sources d'exception, plutôt qu'exemplaires.

Du coup je propose ceci:

- que tu fasses une liste d'algorithmes publics où les explications sont publiées, avec des liens vers ces explications
- qu'on complète avec les liens vers les codes sources quand ils sont publiés
- qu'on dise clairement ce qu'on dit dans cette discussion sur la complémentarité

Mais juste déplacer la section ailleurs laissera la page vide... et nous amènera à l'effacer, alors qu'il paraît naturel d'avoir des exemples.

Qu'est-ce que vous en pensez ?

**Comment by AntoineAugusti** [comment]
Hello,

Il y a des améliorations à faire sur cette page, d'accord, mais je rejoins l'avis de @bzg. Il y a plusieurs niveaux à respecter, du plus simple à mettre en oeuvre au plus compliqué :
- la mention explicite d'un traitement algorithmique sur un avis / une notification / une démarche
- les explications des règles de cet algorithme pouvant être lu par tous, sous la forme d'une page web ou d'un PDF
- la publication du code source de cet algorithme

Je comprends que certains acteurs s'embrouillent avec ces différentes choses mais j'aimerais qu'à terme ces notions soient claires et que les obligations soient respectées au mieux.

Je pense qu'il est important d'avoir une page d'exemples où l'on retrouve des mentions explicites, des règles et des codes sources. Idéalement tout le monde aurait les 3 et toutes les démarches de la France seraient sur cette page. En attendant que ce soit le cas, cette page est intéressante pour montrer où on en est et peut servir de point de départ pour ceux qui veulent mettre en oeuvre leurs obligations.

Cette page d'exemple a selon moi toute sa place dans le guide des algorithmes. C'est rattaché intrinséquement aux algorithmes et ça ne peut pas qu'être considéré comme un code source bien à part dès lors que ce n'est pas exécutable, testé, mal documenté ou publié de manière isolée par rapport au reste des logiciels.

**Comment by bzg** [comment]
Hello !  Je ferme cette ancienne issue - n'hésitez pas à la rouvrir si vous pensez qu'il le faut.
