### ISSUE TITLE
Dead Link sur le guide logiciels

### ISSUE THREAD

**Issue by geoffreyaldebert** [etalab/guides.etalab.gouv.fr#86]
Sur le guide "Codes sources" et sur la page https://guides.etalab.gouv.fr/logiciels/#maintenance-de-ce-document-et-contributions 

Il est fait mention d'un lien vers des issues github qui n'est pas actif : https://github.com/etalab/ouverture-des-codes-sources-publics/issues/new

@bzg

**Comment by bzg** [comment]
Merci !
