### ISSUE TITLE
Définition du NER dans le lexique - guide annotation

### ISSUE THREAD

**Issue by psorianom** [etalab/guides.etalab.gouv.fr#98]
Salut @KimMontalibet ,

Dans la définition NER du lexique du guide d'annotation, il me semble que la tâche d’attribuer des catégories type "verbe", "adjectif" ou "adverbe" est plutôt la tâche du PoS tagging (laquelle, côté machine learning, est en effet très similaire au NER).

> Reconnaissance d'entités nommées
> 
> La reconnaissance d'entités nommées, ou Named Entity Recognition (NER) en anglais, est une tâche d'apprentissage supervisée où les données d'entrées sont chacun des mots d'un document et le label qu'on leur attribue est une catégorie sémantique à laquelle il se rattache : par exemple « verbe », « adjectif » ou « adverbe » dans un cas général et « nom », « prénom », « adresse », « date » pour une tâche de pseudonymisation.
>

**Comment by KimMontalibet** [comment]
J'ai fait la modif ! Merci :)
